# Generated by Django 6.0.6 on 2026-07-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(),
        ),
    ]
